# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
