# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20170502_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
